name: kalkan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  wireguard_vpn: ^0.0.2
  logger: ^2.0.2+1
  font_awesome_flutter: ^10.5.0
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  keystore_generator: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/map.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon.png

  android_12:
    color: "#ffffff"
    image: assets/app_icon.png

